management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  bulkhead:
    instances:
      allStats:
        maxConcurrentCalls: 10
      statsForMessage:
        maxConcurrentCalls: 2